# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{porteo}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Rafael Garcia}, %q{Luis Ciudad}]
  s.date = %q{2011-06-07}
  s.description = %q{Send all messages that you want in any protocol, its ready to send mail messages, twitts and sms with the apropiate gateway}
  s.email = [%q{rgarcia@nosolosoftware.biz}, %q{lciudad@nosolosoftware.biz}]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "COPYING",
    "Gemfile.lock",
    "README.markdown",
    "VERSION",
    "examples_helpers/attach.txt",
    "examples_helpers/config/clave.emitter",
    "examples_helpers/config/few-parameters.emitter",
    "examples_helpers/config/nosolosoftware.emitter",
    "examples_helpers/config/templates/alert.mail",
    "examples_helpers/config/templates/attach.mail",
    "examples_helpers/config/templates/dummy.mail",
    "examples_helpers/config/templates/good_formatted.mail",
    "examples_helpers/config/templates/message.twitter",
    "examples_helpers/config/templates/private.sms",
    "examples_helpers/config/templates/small.mail",
    "features/message/custom_config_path.feature",
    "features/message/recover_data_from_emitter.feature",
    "features/message/recover_from_error.feature",
    "features/message/send_a_message.feature",
    "features/message/send_a_message_by_sms.feature",
    "features/message/set_a_receiver.feature",
    "features/message/set_a_template.feature",
    "features/message/set_template_params.feature",
    "features/message/step_definitions/custom_config_path_steps.rb",
    "features/message/step_definitions/recover_data_steps.rb",
    "features/message/step_definitions/recover_from_error_steps.rb",
    "features/message/step_definitions/send_a_message_steps.rb",
    "features/message/step_definitions/set_a_receiver_steps.rb",
    "features/message/step_definitions/set_template_params_steps.rb",
    "features/message/step_definitions/set_template_steps.rb",
    "features/message/support/env.rb",
    "features/protocol/check_template_requires.feature",
    "features/protocol/send_message.feature",
    "features/protocol/set_template_variables.feature",
    "features/protocol/step_definitions/check_template_steps.rb",
    "features/protocol/step_definitions/send_message_steps.rb",
    "features/protocol/step_definitions/set_template_steps.rb",
    "features/protocol/support/env.rb",
    "features/support/env.rb",
    "spec/gateway/pony_spec.rb",
    "spec/gateway/spec_helper.rb",
    "spec/gateway/twitter_spec.rb",
    "spec/protocols/mail_spec.rb",
    "spec/protocols/spec_helper.rb",
    "spec/spec_helper.rb",
    "src/lib/gateways/gateway.rb",
    "src/lib/gateways/mensario_gateway.rb",
    "src/lib/gateways/pony_gateway.rb",
    "src/lib/gateways/twitter_gateway.rb",
    "src/lib/message.rb",
    "src/lib/protocols/mail_protocol.rb",
    "src/lib/protocols/protocol.rb",
    "src/lib/protocols/sms_protocol.rb",
    "src/lib/protocols/twitter_protocol.rb"
  ]
  s.homepage = %q{http://github.com/nosolosoftware/porteo}
  s.licenses = [%q{GPL-3}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{A Ruby gem for sending all kind of messages}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<pony>, ["~> 1.2"])
      s.add_runtime_dependency(%q<mensario>, ["~> 0.2.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<bluecloth>, ["~> 2.1.0"])
    else
      s.add_dependency(%q<twitter>, ["~> 1.5.0"])
      s.add_dependency(%q<pony>, ["~> 1.2"])
      s.add_dependency(%q<mensario>, ["~> 0.2.0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<bluecloth>, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<twitter>, ["~> 1.5.0"])
    s.add_dependency(%q<pony>, ["~> 1.2"])
    s.add_dependency(%q<mensario>, ["~> 0.2.0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
    s.add_dependency(%q<yard>, ["~> 0.7.1"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<bluecloth>, ["~> 2.1.0"])
  end
end

