# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{porteo}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael Garcia", "Luis Ciudad"]
  s.date = %q{2011-07-20}
  s.description = %q{Send all messages that you want in any protocol, its ready to send mail messages, twitts and sms with the apropiate gateway}
  s.email = ["rgarcia@nosolosoftware.biz", "lciudad@nosolosoftware.biz"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "COPYING",
    "README.markdown",
    "VERSION",
    "lib/gateways/gateway.rb",
    "lib/gateways/mensario_gateway.rb",
    "lib/gateways/pony_gateway.rb",
    "lib/gateways/twitter_gateway.rb",
    "lib/message/message.rb",
    "lib/porteo.rb",
    "lib/protocols/mail_protocol.rb",
    "lib/protocols/protocol.rb",
    "lib/protocols/sms_protocol.rb",
    "lib/protocols/twitter_protocol.rb",
    "porteo.gemspec"
  ]
  s.homepage = %q{http://github.com/nosolosoftware/porteo}
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A Ruby gem for sending all kind of messages}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, ["~> 1.5.0"])
      s.add_runtime_dependency(%q<pony>, ["~> 1.2"])
      s.add_runtime_dependency(%q<mensario>, ["~> 0.2.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<bluecloth>, ["~> 2.1.0"])
    else
      s.add_dependency(%q<twitter>, ["~> 1.5.0"])
      s.add_dependency(%q<pony>, ["~> 1.2"])
      s.add_dependency(%q<mensario>, ["~> 0.2.0"])
      s.add_dependency(%q<rake>, ["~> 0.9.2"])
      s.add_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<bluecloth>, ["~> 2.1.0"])
    end
  else
    s.add_dependency(%q<twitter>, ["~> 1.5.0"])
    s.add_dependency(%q<pony>, ["~> 1.2"])
    s.add_dependency(%q<mensario>, ["~> 0.2.0"])
    s.add_dependency(%q<rake>, ["~> 0.9.2"])
    s.add_dependency(%q<yard>, ["~> 0.7.1"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<bluecloth>, ["~> 2.1.0"])
  end
end

